/**
 * init_db.js
 * Initialize SQLite database (data.db) and seed sample data including `story` and `photo`.
 * Also creates an FTS5 virtual table users_fts for full-text search on name+story.
 *
 * Run: npm run init-db
 */

const Database = require('better-sqlite3');
const path = require('path');
const fs = require('fs');

const DB_FILE = path.join(__dirname, 'data.db');
if (fs.existsSync(DB_FILE)) {
  console.log('Existing DB found at', DB_FILE, '- it will be reused/updated.');
} else {
  console.log('Creating DB at', DB_FILE);
}

const db = new Database(DB_FILE);

// Create users table
 db.exec(`
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  country TEXT,
  city TEXT,
  story TEXT,
  photo TEXT
);
`);

function ensureFtsTable() {
  db.exec(`CREATE VIRTUAL TABLE IF NOT EXISTS users_fts USING fts5(name, story, content='users', content_rowid='rowid');`);
}

// Create FTS5 virtual table
try {
  ensureFtsTable();
} catch (e) {
  console.warn('Could not create users_fts FTS5 table. Ensure SQLite has FTS5 support. Error:', e.message);
}

const seed = [
  { id: '1', name: 'Anil',    country: 'USA',    city: 'Texas',       story: "Anil grew up in a small town in Texas. He loves road trips and barbecues. He started coding to automate tasks at his job and now builds small productivity tools in his spare time.", photo: `https://i.pravatar.cc/150?u=anil` },
  { id: '2', name: 'Ajay',    country: 'India',  city: 'Chennai',     story: "Ajay is a frontend developer from Chennai. He enjoys Tamil cinema, classical music, and experimenting with UI animations.", photo: `https://i.pravatar.cc/150?u=ajay` },
  { id: '3', name: 'Pavan',   country: 'USA',    city: 'Kansas',      story: "Pavan moved to Kansas for university and discovered a passion for data science. On weekends he volunteers teaching kids to code.", photo: `https://i.pravatar.cc/150?u=pavan` },
  { id: '4', name: 'Deepthi', country: 'India',  city: 'Andhra',      story: "Deepthi is a product manager who enjoys solving user problems. She often sketches flows on sticky notes and drinks strong coffee.", photo: `https://i.pravatar.cc/150?u=deepthi` },
  { id: '5', name: 'Vamsi',   country: 'India',  city: 'Hyderabad',   story: "Vamsi is an engineer and amateur photographer. He documents city life and local festivals through his lens.", photo: `https://i.pravatar.cc/150?u=vamsi` },
  { id: '6', name: 'Ravi',    country: 'India',  city: 'Bangalore',   story: "Ravi is into DevOps and cloud infrastructure. He likes mountain biking and building lego robots.", photo: `https://i.pravatar.cc/150?u=ravi` },
  { id: '7', name: 'Sara',    country: 'Canada', city: 'Toronto',     story: "Sara is a UX designer who loves board games and exploring Toronto's food scene.", photo: `https://i.pravatar.cc/150?u=sara` },
  { id: '8', name: 'John',    country: 'USA',    city: 'Seattle',     story: "John is a backend engineer fond of espresso and open-source contributions. He also mentors junior developers.", photo: `https://i.pravatar.cc/150?u=john` },
  { id: '9', name: 'Maria',   country: 'Mexico', city: 'Guadalajara', story: "Maria is an entrepreneur running a small artisan shop. She enjoys ceramics and community markets.", photo: `https://i.pravatar.cc/150?u=maria` },
  { id: '10', name: 'Lee',    country: 'China',  city: 'Shenzhen',    story: "Lee works on embedded systems and enjoys building DIY hardware projects with friends.", photo: `https://i.pravatar.cc/150?u=lee` }
];

const insert = db.prepare('INSERT OR REPLACE INTO users (id, name, country, city, story, photo) VALUES (?, ?, ?, ?, ?, ?);');
const txn = db.transaction((rows) => { for (const r of rows) insert.run(r.id, r.name, r.country, r.city, r.story, r.photo); });
txn(seed);

// Rebuild FTS table
try {
  db.exec('DELETE FROM users_fts;');
  const ftsInsert = db.prepare('INSERT INTO users_fts(rowid, name, story) VALUES (?, ?, ?);');
  const users = db.prepare('SELECT rowid, name, story FROM users').all();
  const txn2 = db.transaction((rows) => { for (const r of rows) ftsInsert.run(r.rowid, r.name || '', r.story || ''); });
  txn2(users);
  console.log('FTS5 users_fts populated.');
} catch (e) {
  console.warn('Could not populate users_fts (FTS5). Trying to rebuild table. Error:', e.message);
  try {
    db.exec('DROP TABLE IF EXISTS users_fts;');
    ensureFtsTable();
    const ftsInsert = db.prepare('INSERT INTO users_fts(rowid, name, story) VALUES (?, ?, ?);');
    const users = db.prepare('SELECT rowid, name, story FROM users').all();
    const txn2 = db.transaction((rows) => { for (const r of rows) ftsInsert.run(r.rowid, r.name || '', r.story || ''); });
    txn2(users);
    console.log('FTS5 users_fts rebuilt and populated.');
  } catch (rebuildErr) {
    console.warn('Could not rebuild users_fts (FTS5). Error:', rebuildErr.message);
  }
}

// Add autogenerated rows to reach ~200 for pagination testing
const countRow = db.prepare('SELECT COUNT(*) AS cnt FROM users').get();
const count = countRow.cnt;
if (count < 200) {
  const moreInsert = db.prepare('INSERT OR IGNORE INTO users (id, name, country, city, story, photo) VALUES (?, ?, ?, ?, ?, ?);');
  const txn3 = db.transaction(() => {
    for (let i = count + 1; i <= 200; i++) {
      moreInsert.run(String(i), `User${i}`, i % 2 === 0 ? 'India' : 'USA', `City${i}`, `This is an autogenerated profile for User${i}. They are user number ${i} for testing pagination and story viewing.`, `https://i.pravatar.cc/150?u=user${i}`);
    }
  });
txn3();
  try {
    const ftsInsert2 = db.prepare('INSERT INTO users_fts(rowid, name, story) VALUES (?, ?, ?);');
    const newUsers = db.prepare('SELECT rowid, name, story FROM users WHERE rowid > ?').all(count);
    const txn4 = db.transaction((rows) => { for (const r of rows) ftsInsert2.run(r.rowid, r.name || '', r.story || ''); });
txn4(newUsers);
    console.log('Seeded additional rows and updated FTS.');
  } catch (e) {
    console.warn('Could not update users_fts for additional rows. Error:', e.message);
  }
}

console.log('DB initialization complete.');
db.close();
